<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIt3wBon\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIt3wBon/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerIt3wBon.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerIt3wBon\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerIt3wBon\App_KernelDevDebugContainer([
    'container.build_hash' => 'It3wBon',
    'container.build_id' => '81835685',
    'container.build_time' => 1601202914,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIt3wBon');
