<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerH2pl5w9\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerH2pl5w9/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerH2pl5w9.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerH2pl5w9\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerH2pl5w9\App_KernelDevDebugContainer([
    'container.build_hash' => 'H2pl5w9',
    'container.build_id' => 'ab1d9ba1',
    'container.build_time' => 1584303914,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerH2pl5w9');
