<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], []],
    'homepage' => [[], ['_controller' => 'App\\Controller\\CoinController::coinsList'], [], [['text', '/']], [], []],
    'coin' => [['coin'], ['_controller' => 'App\\Controller\\CoinController::coin'], [], [['variable', '/', '[^/]++', 'coin', true], ['text', '/coin']], [], []],
    'exchanges' => [[], ['_controller' => 'App\\Controller\\ExchangeController::exchangesList'], [], [['text', '/exchanges']], [], []],
    'exchange' => [['exchange'], ['_controller' => 'App\\Controller\\ExchangeController::exchange'], [], [['variable', '/', '[^/]++', 'exchange', true], ['text', '/exchange']], [], []],
    'search' => [[], ['_controller' => 'App\\Controller\\SearchController::search'], [], [['text', '/search']], [], []],
];
